services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-ruby
      dockerfile: Dockerfile
    image: backend-for-frontend-ruby:latest
    pull_policy: never
    ports:
      - "127.0.0.1:10115:10115"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=backend-for-frontend
    depends_on:
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started

  image-picker:
    build:
      context: services/image-picker-ruby
      dockerfile: Dockerfile
    image: image-picker-ruby:latest
    pull_policy: never
    ports:
      - "127.0.0.1:10116:10116"
    environment:
      - BUCKET_NAME
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-ruby

  meminator:
    build:
      context: services/meminator-ruby
      dockerfile: Dockerfile
    image: meminator-ruby:latest
    pull_policy: never
    ports:
      - "127.0.0.1:10117:10117"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-ruby

  phrase-picker:
    build:
      context: services/phrase-picker-ruby
      dockerfile: Dockerfile
    image: phrase-picker-ruby:latest
    pull_policy: never
    ports:
      - "127.0.0.1:10118:10118"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-ruby

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      args:
        - HONEYCOMB_API_KEY
    image: web:latest
    pull_policy: never
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114"
    depends_on:
      backend-for-frontend:
        condition: service_healthy

